/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(header_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ab99b1288c32a6fe4239031fc4e0c745)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora_sdr/header_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <header_decoder_pydoc.h>

void bind_header_decoder(py::module& m)
{

    using header_decoder    = ::gr::lora_sdr::header_decoder;


    py::class_<header_decoder, gr::block, gr::basic_block,
        std::shared_ptr<header_decoder>>(m, "header_decoder", D(header_decoder))

        .def(py::init(&header_decoder::make),
           py::arg("impl_head"),
           py::arg("cr"),
           py::arg("pay_len"),
           py::arg("has_crc"),
           D(header_decoder,make)
        )
        



        ;




}








